spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coffee
    username: root
    password: 12345678
  data:
    redis:
      host: localhost
      port: 6379

portone:
  api:
    secret: ldebLabDdRMdG4ITfq5pOBzrvr6Fxm84lajoVAE2YrEuSSLhVtQF40BekT3Q3Hobjvbk5WTZbx8W4tW5
    base-url: https://api.portone.io
